### ISSUE TITLE
TheoryData with MemberAutoMockData no longer works with xunit 2.9.2

### ISSUE THREAD

**Issue by dalyIsaac** [Accenture/AutoFixture.XUnit2.AutoMock#152]
I'm not a user of this library, but I recently encountered an issue (https://github.com/xunit/xunit/issues/3034) which this library also suffers from:

XUnit 2.9.2[^1] introduced specific handling of `TheoryData` which prevents `ConvertDataItem` being called in `MemberAutoDataBaseAttribute`.

I fixed this by pulling more logic into my own `MemberAutoDataBaseAttribute` lookalike.

[^1]: https://github.com/xunit/xunit/commit/0f8f1563876f2cbbb9af27e0bb14b824372fd4a8#diff-e977fc17c9612438c073c7620c84f91c706c581b8f6d990b9e5be748fc096432R77

**Comment by piotrzajac** [comment]
@dalyIsaac thank you for reporting the issue. It was fixed in version [3.6.2](https://github.com/Accenture/AutoFixture.XUnit2.AutoMock/releases/tag/3.6.2)
